In [ ]:
import psycopg2

#establishing the connection
conn = psycopg2.connect (
   database="index", user='postgres', password='3214', host='127.0.0.1', port= '5432'
)
conn.autocommit = True
 
# Creating a cursor object
cursor = conn.cursor()
 
# query to create a database
sql = "CREATE database Index" 
 
# executing above query 
cursor.execute(sql)
print("Database has been created successfully !!")
 
# Closing the connection
conn.close()

In [26]:
import psycopg2

#establishing the connection
conn = psycopg2.connect (
   database="index", user='postgres', password='3214', host='127.0.0.1', port= '5432'
)
conn.autocommit = True
 
# Creating a cursor object
cursor = conn.cursor()
 
# query to create a database
sql = "CREATE TABLE index (id SERIAL,title VARCHAR(250),page_link VARCHAR(500),thumbnail VARCHAR(500), PRIMARY KEY (id))"
 
# executing above query 
cursor.execute(sql)
print("table has been created successfully !!")
 
# Closing the connection
conn.close()

table has been created successfully !!

In [1]:
import psycopg2
import os
import csv 

#establishing the connection
conn = psycopg2.connect (
   database="index", user='postgres', password='3214', host='127.0.0.1', port= '5432'
)
conn.autocommit = True
 
# Creating a cursor object
cursor = conn.cursor()
 
# query to create a database
csv_file = r'listtocsv1.csv'
folder_add =r'E:\supreme-commander\supreme-commander\web scraper\test-notebook'
csv_file_path = os.path.join(folder_add,csv_file)
#E:\supreme-commander\supreme-commander\web scraper\test-notebook\listtocsv1.csv
#sql = "COPY index(title, page_link, thumbnail) FROM 'E:\\supreme-commander\\supreme-commander\\web scraper\\test-notebook\\demo_csv.csv'  DELIMITER ',' CSV HEADER;"
import csv

insert = 'INSERT INTO index (title, page_link, thumbnail) VALUES( )'
  
# Open file 
with open(csv_file_path) as file_obj:
      
    # Create reader object by passing the file 
    # object to reader method
    reader_obj = csv.reader(file_obj)
      
    # Iterate over each row in the csv 
    # file using reader object
    for row in reader_obj:
        cursor.execute(f"INSERT INTO index (title, page_link, thumbnail) VALUES('{row[0]}','{row[1]}','{row[2]}')")
        
# executing above query 
    

print("csv inserted!!")
 
# Closing the connection
conn.close()

IndexError: list index out of range

In [23]:
import psycopg2
import os

#establishing the connection
conn = psycopg2.connect (
   database="index", user='postgres', password='3214', host='127.0.0.1', port= '5432'
)
conn.autocommit = True
 
# Creating a cursor object
cursor = conn.cursor()
 
# query 

sql = "SELECT * FROM index;"
 
# executing above query 
cursor.execute(sql)

print(cursor.fetchall())
 
# Closing the connection
conn.close()

[(1, 'Tales of Demons and Gods', 'https://readmanganato.com/manga-ax951880', 'https://avt.mkklcdnv6temp.com/19/v/1-1583464475.jpg'), (2, 'Solo Leveling', 'https://readmanganato.com/manga-dr980474', 'https://avt.mkklcdnv6temp.com/30/a/17-1583496340.jpg'), (3, 'Martial Peak', 'https://readmanganato.com/manga-bn978870', 'https://avt.mkklcdnv6temp.com/20/b/16-1583494192.jpgGIT '), (4, 'Apotheosis', 'https://readmanganato.com/manga-bt978676', 'https://avt.mkklcdnv6temp.com/13/f/16-1583493949.jpg'), (5, 'Versatile Mage', 'https://readmanganato.com/manga-bf979214', 'https://avt.mkklcdnv6temp.com/33/a/16-1583494657.jpg'), (6, 'Star Martial God Technique', 'https://readmanganato.com/manga-wj973392', 'https://avt.mkklcdnv6temp.com/32/i/14-1583490877.jpg'), (7, "A Returner's Magic Should Be Special", 'https://readmanganato.com/manga-ci980191', 'https://avt.mkklcdnv6temp.com/19/m/17-1583495960.jpg'), (8, 'The Beginning After the End', 'https://readmanganato.com/manga-dg980989', 'https://avt.mkklcdnv6temp.com/48/q/17-1583497020.jpg'), (9, 'Kimetsu no Yaiba', 'https://readmanganato.com/manga-to970571', 'https://avt.mkklcdnv6temp.com/30/e/13-1583488820.jpg'), (10, 'One Piece', 'https://readmanganato.com/manga-aa951409', 'https://avt.mkklcdnv6temp.com/3/u/1-1583463814.jpg'), (11, 'Rebirth Of The Urban Immortal Cultivator', 'https://readmanganato.com/manga-fr982926', 'https://avt.mkklcdnv6temp.com/19/o/19-1583499863.jpg'), (12, 'Komi-san wa Komyushou Desu', 'https://readmanganato.com/manga-va953509', 'https://avt.mkklcdnv6temp.com/25/s/2-1583466695.jpg'), (13, 'God of Martial Arts', 'https://readmanganato.com/manga-ah978064', 'https://avt.mkklcdnv6temp.com/5/a/16-1583493642.jpg'), (14, 'My Wife Is a Demon Queen', 'https://readmanganato.com/manga-dk980967', 'https://avt.mkklcdnv6temp.com/18/j/26-1656934348.jpg'), (15, 'Tensei Shitara Slime Datta Ken', 'https://readmanganato.com/manga-tz953334', 'https://avt.mkklcdnv6temp.com/19/y/2-1583466482.jpg'), (16, 'Mushoku Tensei - Isekai Ittara Honki Dasu', 'https://readmanganato.com/manga-qm951521', 'https://avt.mkklcdnv6temp.com/7/r/1-1583463967.jpg')]

In [116]:
import psycopg2
import os

#establishing the connection
conn = psycopg2.connect (
   database="index", user='postgres', password='3214', host='127.0.0.1', port= '5432'
)
conn.autocommit = True
 
# Creating a cursor object
cursor = conn.cursor()

cursor.execute("""SELECT relname FROM pg_class WHERE relkind='r'
                  AND relname !~ '^(pg_|sql_)';""") # "rel" is short for relation.

tables = [i[0] for i in cursor.fetchall()] # A list() of tables.

print(cursor.fetchall())
 
# Closing the connection
conn.close()

[]

In [111]:
import psycopg2
import os

#establishing the connection
conn = psycopg2.connect (
   database="index", user='postgres', password='3214', host='127.0.0.1', port= '5432'
)
conn.autocommit = True
 
# Creating a cursor object
cursor = conn.cursor()
 
# query to fetch all tables

sql = "SELECT datname FROM pg_database"
 
# executing above query 
cursor.execute(sql)

print(cursor.fetchall())
 
# Closing the connection
conn.close()

[('template1',), ('template0',), ('index',)]

TypeError: can only concatenate list (not "int") to list

In [96]:
df.to_sql('db_table2', engine, if_exists='replace')

In [119]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:3214@127.0.0.1:5432/index')



 
# Skipping 2 rows from start in csv
# and initialize it to a  dataframe
df = pd.read_csv("listtocsv1.csv", skiprows = 1, header=None)
df.columns = ["title","link","thumbnail"]
df['id'] = range(1, len(df) + 1)
df=df.set_index('id')
df.to_sql('listtocsv1.csv', engine, if_exists='replace') #insert dataframe into database


 
# Show the dataframe
df

,title,link,thumbnail
id,,,
1,Tales of Demons and Gods,https://readmanganato.com/manga-ax951880,https://avt.mkklcdnv6temp.com/19/v/1-158346447...
2,Solo Leveling,https://readmanganato.com/manga-dr980474,https://avt.mkklcdnv6temp.com/30/a/17-15834963...
3,Martial Peak,https://readmanganato.com/manga-bn978870,https://avt.mkklcdnv6temp.com/20/b/16-15834941...
4,Apotheosis,https://readmanganato.com/manga-bt978676,https://avt.mkklcdnv6temp.com/13/f/16-15834939...
5,Versatile Mage,https://readmanganato.com/manga-bf979214,https://avt.mkklcdnv6temp.com/33/a/16-15834946...
...,...,...,...
35498,7 Nichikan de Shinu Joshikousei to Shinigami n...,https://mangakakalot.com/manga/zh932680,https://avt.mkklcdnv6temp.com/16/h/29-16797180...
35499,Shinigami no Hanayome,https://readmanganato.com/manga-rp995150,https://avt.mkklcdnv6temp.com/16/i/29-16797181...
35500,That Time Only Akari Got Reincarnated as a Slime,https://mangakakalot.com/manga/hi932682,https://avt.mkklcdnv6temp.com/16/j/29-16797183...
35501,Mikazuki March,https://mangakakalot.com/manga/pe932655,https://avt.mkklcdnv6temp.com/15/g/29-16796314...
35502,Sayonara Daisy,https://readmanganato.com/manga-rx995132,https://avt.mkklcdnv6temp.com/15/q/29-16796336...